<script setup lang="ts">
import LeagueService from '@/services/league'
import { Federation } from '@/domain/federation'
import { ApiLeagueFormRequest } from '@/types/api/league'
import { League, mapLeagueToApiLeagueFormRequest } from '@/domain/league'
import { Division } from '@/domain/division'
import { Category } from '@/domain/game'
import { Gender } from '@/domain/game'
import { ApiErrorObject } from '@/types/errors'

const props = defineProps({
  league: {
    type: Object as PropType<League>,
    required: false,
  },
  federation: {
    type: Object as PropType<Federation>,
    required: true,
  },
})

const emit = defineEmits<{
  (e: 'league:created', value: League): void
  (e: 'league:updated', value: League): void
  (e: 'refresh', value: boolean): void
}>()

const { t } = useI18n()
const toast = useEasyToast()
const leagueService = new LeagueService()

const minYear: number = new Date(
  props.league?.start ? props.league.start : new Date(),
).getFullYear()
const namePlaceholder: string = t('leagues.name_autogenerated')

const form = ref<ApiLeagueFormRequest>(
  mapLeagueToApiLeagueFormRequest(props.league, props.federation.id),
)

const selectedDivision = ref<Division>()
const selectedCategory = ref<Category>()
const selectedGender = ref<Gender>()
const loadingApi = ref<boolean>(false)
const errors = ref<ApiErrorObject>()

const federationGroupedDivisions = computed(() => {
  const federations = []

  if (
    props.federation.federation &&
    props.federation.federation.divisions?.length
  ) {
    federations.push(props.federation.federation)
  }

  if (props.federation.divisions?.length) {
    federations.push(props.federation)
  }

  return federations
})

const seasonString = computed(() => {
  if (props.league?.start && props.league?.end) {
    const start = new Date(props.league.start)
    const end = new Date(props.league.end)
    return `${start.getFullYear()}-${end.getFullYear()}`
  }

  if (form.value.season) {
    return String(form.value.season)
  }

  return ''
})

const setFormData = (league: League) => {
  form.value = mapLeagueToApiLeagueFormRequest(league, props.federation.id)

  if (league.division) handleDivisionSelected(league.division)
  if (league.category) handleCategorySelected(league.category)
  if (league.gender) handleGenderSelected(league.gender)
}

const handleSubmit = () => {
  !!props.league ? handleUpdate() : handleStore()
}

const handleStore = async () => {
  loadingApi.value = true

  const { data, error } = await leagueService.store(form.value)

  if (error.value) {
    toast.mapError(Object.values(error.value?.data?.errors))
    errors.value = error.value.data?.errors
    loadingApi.value = false
  } else if (data.value) {
    toast.success(t('leagues.created'))
    // emit('league:created', mapApiLeagueToLeague(data.value.data.league))
    navigateTo(`/leagues/${data.value.data.league.id}`)
  }
}

const handleUpdate = async () => {
  loadingApi.value = true

  const { data, error } = await leagueService.update(form.value.id, form.value)

  if (error.value) {
    toast.mapError(Object.values(error.value?.data?.errors), false)
    errors.value = error.value.data?.errors
    loadingApi.value = false
  } else if (data.value) {
    toast.success(t('leagues.updated'))
    // emit('league:updated', mapApiLeagueToLeague(data.value.data.league))
    navigateTo(`/leagues/${data.value.data.league.id}`)
  }
}

const handleDivisionSelected = (division: Division) => {
  selectedDivision.value = division
  form.value.division_id = division.id
}

const handleCategorySelected = (category: Category) => {
  selectedCategory.value = category
  form.value.category_id = category.id
}

const handleGenderSelected = (gender: Gender) => {
  selectedGender.value = gender
  form.value.gender_id = gender.id
}

watch(
  () => props.league,
  value => {
    if (value) {
      setFormData(value)
    }
  },
  {
    immediate: true,
  },
)

watch(
  form,
  () => {
    form.value.name =
      selectedDivision.value && seasonString.value
        ? `${selectedDivision.value.name} ${seasonString.value}`
        : selectedDivision.value?.name ?? ''
    errors.value = undefined
  },
  { deep: true },
)

defineExpose({
  handleSubmit,
  loadingApi,
})
</script>

<template>
  <form class="easy-league-form-component" @submit.prevent="handleSubmit">
    <EasyGrid :breakpoints="{ sm: 2, lg: 3, xl: 4 }" :gap="3">
      <FormLabel :label="t('leagues.name')" :error="errors?.name?.[0]" required>
        <InputText
          v-model="form.name"
          :placeholder="namePlaceholder"
          readonly
        />
      </FormLabel>

      <FormLabel
        :label="t('leagues.season')"
        :error="errors?.season?.[0]"
        required
      >
        <InputNumber
          v-model="form.season"
          :min="minYear"
          :useGrouping="false"
          showButtons
        />
      </FormLabel>

      <FormLabel :label="t('federations.federation')">
        <InputText
          :value="federation.name"
          required
          readonly
          :error="errors?.federation_id?.[0]"
        />
      </FormLabel>

      <FormLabel
        :label="t('divisions.division')"
        required
        :error="errors?.division_id?.[0]"
      >
        <DivisionSelector
          v-model="selectedDivision"
          :groupedDivisions="federationGroupedDivisions"
          @division:selected="handleDivisionSelected"
        />
      </FormLabel>

      <FormLabel
        :label="t('categories.category')"
        required
        :error="errors?.category_id?.[0]"
      >
        <CategorySelector
          v-model="selectedCategory"
          @category:selected="handleCategorySelected"
        />
      </FormLabel>

      <FormLabel
        :label="t('genders.gender')"
        required
        :error="errors?.gender_id?.[0]"
      >
        <GenderSelector
          v-model="selectedGender"
          @gender:selected="handleGenderSelected"
        />
      </FormLabel>
    </EasyGrid>

    <FormFooterActions
      class="mt-10"
      :loading="loadingApi"
      :submitLabel="props.league ? t('leagues.update') : t('leagues.create')"
      hideCancel
      stickyBreakpoint="sm"
      @form:submit="handleSubmit"
    />
  </form>
</template>

<script lang="ts">
export default {
  name: 'LeagueForm',
}
</script>
